### ISSUE TITLE
Add and config prettier in this project

### ISSUE THREAD

**Issue by AbraaoAlves** [RodrigoNet0/newsletter#7]
## Problem

Many source files have little problems with formatting. to avoid handling it by yourself and spend time reviewing these problems, you need to add a tool to take care of them.

## Solution

Add and config [Prettier](https://prettier.io/) in this project to auto formatting: 

### Benefits

- No effort spent fixing formatting
- No need to look up rules in a style guide
- No time wasted discussing style in pull requests
- When the style guide changes (or when it is first introduced) Prettier can automatically apply it across the whole code base.
- Code copied from another project or from StackOverflow automatically adjusts

**Comment by RodrigoNet0** [comment]
I added Prettier, but the documentation didn't fully clarify how to set it up, I'd like some examples.
